version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    # Cleaner approach: let the .env file handle all the variables smoothly
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis
      - mlflow
    networks:
      - algoforge_network
    volumes:
      - ./models/saved:/app/models/saved
      - ./data/raw:/app/data/raw
      - ./mlruns:/app/mlruns

  mlflow:
    image: ghcr.io/mlflow/mlflow
    ports:
      - "5000:5000"
    environment:
      - GUNICORN_CMD_ARGS=--trust-proxy-headers --forwarded-allow-ips=*
    networks:
      - algoforge_network
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --backend-store-uri /mlruns --default-artifact-root /mlruns --host 0.0.0.0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - algoforge_network
    volumes:
      - redis_data:/data

volumes:
  redis_data:

networks:
  algoforge_network:
    driver: bridge