import pytest
from fastapi.testclient import TestClient
from api.main import app

# Create a synchronous test client
client = TestClient(app)


def test_get_models():
    """Test that the API correctly returns the list of available models."""
    response = client.get("/models")
    assert response.status_code == 200
    data = response.json()
    assert len(data) > 0
    # check the random forest classifier is in the list
    assert any(model["name"] == "Random Forest Classifier" for model in data)

def test_get_datasets():
    """Test that the API correctly returns the list of available datasets."""
    response = client.get("/datasets")
    assert response.status_code == 200
    data = response.json()
    assert len(data) > 0
    # check the iris dataset is in the list
    assert any(dataset["name"] == "iris" for dataset in data)

def test_full_train_and_predict_lifecycle():
    """Integration Test: Train a model and immediately use it to predict."""
    # train the model
    train_payload = {
        "model_type": "Random Forest Classifier",
        "dataset_name": "iris",
        "target_column": "target",
        "test_size": 0.2,
        "drop_columns": [],
        "random_state": 42,
    }

    train_res = client.post("/train", json=train_payload)
    # Print the exact error if it fails
    if train_res.status_code != 200:
        print("\n FASTAPI ERROR:", train_res.json(), "\n")
    assert train_res.status_code == 200

    train_data = train_res.json()
    assert "model_id" in train_data
    assert train_data["task_type"] == "classification"
    assert "metrics" in train_data

    # save the model id generated by the training endpoint
    model_id = train_data["model_id"]

    # use the model to predict
    # Iris features: sepal length, sepal width, petal length, petal width
    predict_payload = {
        "model_id": model_id,
        "features": {
            "sepal_length": 5.1,
            "sepal_width": 3.5,
            "petal_length": 1.4,
            "petal_width": 0.2,
        },
    }

    predict_res = client.post("/predict", json=predict_payload)
    assert predict_res.status_code == 200


    predict_data = predict_res.json()
    assert predict_data["model_id"] == model_id

    # We expect the translation dictionary to convert the 0/1/2 back to text
    assert isinstance(predict_data["prediction"], str)